name: Build
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sukawasatoru/toolchain-android:1.1
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          GRADLE_OPTS: -Xmx4g
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew --info --stacktrace build
